-- CreateTable
CREATE TABLE "CongregationProfile" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "ageUnder11Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "age11to17Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "age18to24Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "age25to34Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "age35to49Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "age50to74Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ageOver75Pct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "economicPoorPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "economicBelowAvgPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "economicAveragePct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "economicAboveAvgPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "economicRichPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "ethnicGroups" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "educationLevels" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CongregationProfile_pkey" PRIMARY KEY ("id")
);
